autonomous_repository_path: C:/Users/tihor/Projects/HighStakesAutonomous/src/routes.h
max_acceleration: 5
max_jerk: 45
max_velocity: 4
routes_folder_path: C:/Users/tihor/Projects/VexAutonomousPlanner/routes
track_width: 2