autonomous_repository_path: C:/Users/tihor/Projects/HighStakesAutonomous/include/routes/routes.h
max_acceleration: 4.5
max_jerk: 45.0
max_velocity: 5.3
routes_folder_path: C:/Users/tihor/Projects/VexAutonomousPlanner/routes
track_width: 2.08333333333
