actions: test_action
field:
  type: Push Back Match
files:
  autonomous_repository_file: routes.h
  header_folder: /home/tihor/Projects/PushBackAutonomous/include
  routes_folder: /home/tihor/Projects/VexAutonomousPlanner/routes
max_acceleration: 12.0
motion:
  max_acceleration: 12.0
  max_jerk: 43.0
  max_velocity: 4.0
robot:
  length: 15.0
  track_width: 11.5
  visualization: false
  width: 18.0
