autonomous_repository_path: C:/Users/tihor/Projects/HighStakesAutonomous/src/routes.h
max_acceleration: 8
max_jerk: 45
max_velocity: 5
routes_folder_path: C:/Users/tihor/Projects/VexAutonomousPlanner/routes
