autonomous_repository_path: /home/rohit/Projects/HighStakesAutonomous/include/routes/routes.h
max_acceleration: 4.5
max_jerk: 45
max_velocity: 5.3
routes_folder_path: /home/rohit/Projects/VexAutonomousPlanner/routes
track_width: 2
