name: Build Executable

on: workflow_dispatch
  # push:
  #   tags:
  #     - v*

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable on Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --clean -y path_planner.spec

      - name: Build executable on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --clean -y path_planner.spec

      - name: Archive the output
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: executable-${{ matrix.os }}
          path: dist/